### PR TITLE
Remove useBootstrap

### PR DESCRIPTION
**Pull request by neftaly**
This PR removes localStorage (document URL persistence) from useBootstrap. It is intended to enable useBootstrap to be used without a storage adapter, as per #266.

### CODE REVIEW

**Comment by neftaly** [comment]
I think it would be nice to have some logic that detected if storage adapters were defined, though I want to keep the scope small and figure out if this is worth it later. It would be really nice to persist the document URL using whatever storage adapters were in use, but it would probably be a bit too hairy. 

I would like to figure out if the URLs are causing a similar sort of issue w.r.t persistence in a development environment, however I suspect this would be better solved elsewhere in the tooling.

**Comment by neftaly** [comment]
It would be helpful to show an example of localStorage URL persistence in a tutorial or cookbook or similar

**Comment by pvh** [comment]
We talked about this a while back but I think we ought to just deprecate useBootstrap entirely. I agree that the localStorage is the pits but the longer I go, the more I lean towards doing away with it. What do you think?

**Comment by neftaly** [comment]
Sounds good, I would rather this existed in a tutorial or example.

**Comment by neftaly** [comment]
There is still an example using useBootstrap in `packages/automerge-reac-hooks/README.md` (and the identical comment on `packages/automerge-reac-hooks/index.ts`).

I don't have the bandwidth to fix the example though sorry! But it's not urgent and shouldn't affect anything.

**Comment by pvh** [comment]
I had a heap of rebase conflicts so I just reimplemented this but it's done now. Thanks @neftaly.

**Pull request closed without merging**
