### PR TITLE
Remove onInvalidAutomergeUrl from useBootstrap

### PR DESCRIPTION
**Pull request by neftaly**
This PR removes `onInvalidAutomergeUrl` from useBootstrap.

The alternative is to use a react error boundary. From my understanding, this wasn't possible at the time.

### CODE REVIEW

**Comment by neftaly** [comment]
I would like to be able to do something like `error instanceof InvalidAutomergeUrlError` or similar in the error boundary, but this would require a separate PR.

**Comment by pvh** [comment]
I think this is a great idea but is technically a breaking change to the API. I've been hesitant to merge it because of that even though I suspect nobody will be using it.

**Comment by pvh** [comment]
Also, it's worth noting that passing in a bad AutomergeUrl should emit an error from the DocHandle so this is probably totally redundant anyway.

**Comment by pvh** [comment]
Moot with usebootstrap gone.

**Pull request closed without merging**
