### PR TITLE
useDocument listen to delete events

### PR DESCRIPTION
**Pull request by joshuahhh**
Currently useDocument doesn't listen for deletion, so docs stick around post-deletion.

(I'm not 100% sure about how deletion works, so plz lmk if this is off-base.)

### CODE REVIEW

**Comment by pvh** [comment]
Looks good but can you please add a test for this?

**Comment by joshuahhh** [comment]
Sure! As long as I can yak-shave a bite first. See #303 303.

**Comment by joshuahhh** [comment]
The first commit on this PR is from #309; that should get merged first. (Maybe there's a way for me to list this in GitHub? IDK.)

**Comment by pvh** [comment]
Merged -- thanks, Josh.

**Pull request merged**
